name: Convert .py to .ipynb

on:
  push:
    paths:
      - '**.py'
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jupytext
        run: pip install jupytext

      - name: Convert Python files to Jupyter notebooks
        run: |
          PY_FILES=$(find . -name "*.py")
          if [ -z "$PY_FILES" ]; then
            echo "Aucun fichier .py trouvé. On quitte."
            exit 0
          fi
          for file in $PY_FILES; do
            jupytext "$file" --to notebook
          done

      - name: Commit and push converted notebooks
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add '*.ipynb'
          git commit -m "Convert .py to .ipynb [auto]" || echo "No changes to commit"
          git push
